# Generated by Django 5.0.2 on 2024-03-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('MM', 'Memo'), ('TD', 'Trade')], max_length=10),
        ),
    ]
