# Generated by Django 5.0.2 on 2024-03-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0003_note_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='record_date',
            field=models.CharField(max_length=10),
        ),
    ]
