# Generated by Django 5.0.2 on 2024-03-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0005_alter_note_stock_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='stock_data',
        ),
        migrations.AddField(
            model_name='note',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='state',
            field=models.CharField(blank=True, choices=[('SL', 'Sell'), ('BY', 'BUY')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='ticker',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('MM', 'Memo'), ('TD', 'Trade')], max_length=2),
        ),
    ]
