# Generated by Django 5.0.2 on 2024-03-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0006_remove_note_stock_data_note_price_note_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='stock_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='state',
            field=models.CharField(blank=True, choices=[('SL', 'SELL'), ('BY', 'BUY')], max_length=2, null=True),
        ),
    ]
