# Generated by Django 5.0.2 on 2024-04-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0008_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
