# Generated by Django 5.0.2 on 2024-04-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0009_portfolio_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
