# Generated by Django 5.0.2 on 2024-02-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(max_length=10)),
                ('detail_code', models.CharField(max_length=10)),
                ('detail_code_name', models.CharField(max_length=100)),
                ('reference_value', models.CharField(blank=True, max_length=50, null=True)),
                ('use_flag', models.BooleanField(default=True)),
                ('sort_no', models.IntegerField()),
                ('remark', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '공통코드',
            },
        ),
    ]
