# Generated by Django 5.0.2 on 2024-03-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='sort_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
