# Generated by Django 3.1.3 on 2021-12-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=18)),
                ('message', models.CharField(max_length=1000)),
                ('create_date', models.DateTimeField()),
                ('remote_address', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Contact',
            },
        ),
    ]
