# Generated by Django 5.0.2 on 2024-03-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_resultdata_func_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultdata',
            name='soup_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
