# Generated by Django 5.0.2 on 2024-03-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_rename_soup_data_resultdata_base_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultdata',
            name='key_name',
            field=models.CharField(default='KRW2USD', max_length=50),
            preserve_default=False,
        ),
    ]
