# Generated by Django 5.0.2 on 2024-03-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_resultdata_key_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultdata',
            name='user_agent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
