# Generated by Django 5.0.2 on 2024-04-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_alter_resultdata_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultdata',
            name='key_name',
            field=models.CharField(max_length=200),
        ),
    ]
